### ISSUE TITLE
Historiser les cotisations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nivhg/ludopen#105]
```
Sinon, les stats sont fausses : il est nécessaire d'avoir l'historique des 
cotisations pour qu'elles soient juste
```

Original issue reported on code.google.com by `vepa2s...@gmail.com` on 3 Feb 2015 at 5:26

**Comment by nivhg** [comment]
Retrait de la possibilité de modifier une adhésion. La suppression d'une adhésion ne fait que mettre le champs "supprimer" à 1.
